# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reviews',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='av_content',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='av_design',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='av_usability',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
