# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
